"""empty message

Revision ID: bb7f3a5a2d10
Revises: ace228d17949
Create Date: 2023-05-23 13:25:00.651419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb7f3a5a2d10'
down_revision = 'ace228d17949'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('camera', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('lights', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('audio', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('props', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('editing', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('editing', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('editing_software')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('editing_software', sa.BOOLEAN(), nullable=True))
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('editing')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('editing')
        batch_op.drop_column('props')
        batch_op.drop_column('audio')
        batch_op.drop_column('lights')
        batch_op.drop_column('camera')

    # ### end Alembic commands ###
